# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "gtk_treeview_settings"
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kasper Johansen"]
  s.date = "2013-03-08"
  s.description = "A gem that helps with ordering of columns and more."
  s.email = "k@spernj.org"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "gtk_treeview_settings.gemspec",
    "lib/gtk_treeview_settings.rb",
    "spec/gtk_treeview_settings_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/kaspernj/gtk_treeview_settings"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "A gem that helps with ordering of columns and more."

  if s.respond_to? :specification_version
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new("1.2.0")
      s.add_runtime_dependency("knjrbfw", [">= 0"])
      s.add_development_dependency("rspec", ["~> 2.8.0"])
      s.add_development_dependency("rdoc", ["~> 3.12"])
      s.add_development_dependency("bundler", [">= 1.0.0"])
      s.add_development_dependency("jeweler", ["~> 1.8.4"])
    else
      s.add_dependency("knjrbfw", [">= 0"])
      s.add_dependency("rspec", ["~> 2.8.0"])
      s.add_dependency("rdoc", ["~> 3.12"])
      s.add_dependency("bundler", [">= 1.0.0"])
      s.add_dependency("jeweler", ["~> 1.8.4"])
    end
  else
    s.add_dependency("knjrbfw", [">= 0"])
    s.add_dependency("rspec", ["~> 2.8.0"])
    s.add_dependency("rdoc", ["~> 3.12"])
    s.add_dependency("bundler", [">= 1.0.0"])
    s.add_dependency("jeweler", ["~> 1.8.4"])
  end
end
